---

- name: Check if keystore is already set up
  stat: path={{ jira_user_home_dir }}/.keystore
  register: ssl

- name: Generate the Java KeyStore
  command: keytool -genkey -noprompt -alias {{ ssl_alias }} -keyalg RSA  -dname {{ ssl_dname }} -storepass {{ ssl_storepass }} -keypass {{ ssl_keypass }} -validity 3650
  su: yes
  su_user: "{{ jira_user }}"
  when: not ssl.stat.exists

- name: Change JIRA to use SSL
  template: src=server.xml.j2 dest={{ jira_user_home_dir }}/current/conf/server.xml owner={{ jira_user }} group={{ jira_user_group }} mode=0644
